#!/bin/bash -e
#
# S2I run script for the 'springboot-sti' image.
# The run script executes the server that runs your application.
#
# For more information see the documentation:
#	https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
#


if [ -z "$TIMEZONE" ]; then
	echo "···································································································"
	echo "---->  VARIABLE TIMEZONE NO SETEADA - INICIANDO CON VALORES POR DEFECTO"
	echo "---->  POSIBLES VALORES: America/Montevideo | America/El_Salvador"
	echo "···································································································"
else
	echo "···································································································"
	echo "---->  TIMEZONE SETEADO ENCONTRADO: " $TIMEZONE
	echo "···································································································"
	cat /usr/share/zoneinfo/$TIMEZONE > /etc/localtime && \
	echo $TIMEZONE > /etc/timezone
fi



if [ ! -z "$WAITFOR_HOST" ] && [ ! -z "$WAITFOR_PORT" ] ; then
	echo "···································································································"
	echo "---->  WAITFOR  ACTIVADO.."
    until nc -z -v -w5 $WAITFOR_HOST $WAITFOR_PORT &> /dev/null; do echo waiting for $WAITFOR_HOST; sleep 15; done;	
	echo "···································································································"
fi


if [ ! -f "/etc/kong-init/.nodelete" ]; then
    touch /etc/kong-init/.nodelete
	echo "···································································································"
    echo "--> FIRST START CHECK MIGRATIONS.."
    kong migrations bootstrap -c /etc/kong/kong.conf || rm -rf /etc/kong-init/.nodelete
	curl -X POST http://127.0.0.1:8001/plugins --data "name=prometheus"
	curl -X POST http://127.0.0.1:8001/plugins --data "name=key-auth"
	echo "···································································································"
fi


echo "INICIANDO KONG.."
exec kong start --v --vv -c /etc/kong/kong.conf
